image: node:8.12.0

stages:
  - lint
  - test

lint:
  stage:
    lint
  script:
  - "echo linting"
  - rm -rf node_modules
  - npm install
  - npm run lint

test:
  stage:
    test
  script:
  - "echo testing"
  - rm -rf node_modules
  - npm install
  - npm run test
