language: node_js
node_js:
- 8
deploy:
  skip_cleanup: true
  provider: npm
  email: sanda.contiu@philips.com
  api_key:
    secure: E7jOj2fv8b/ZM+390u1uO/qRUhlAZIPqzJSO78uOaf3kVLtLKliWRhHEl/lT2fmoHmRmJThCcnnVUOzOIf2O1tF3kLbSvMdMv1E+MZHgrtXfWcz0yN+ab8VeDr4SCeaDzO4/q27n3sojtlXgKAI5niMnEIH+bFM+Rh39Cx8pS2ktLHSOtVORZ9D/E9Ne54iN3gtlVAqWUsHve6C9jMXvpsBo8UglhjJUpgJ4NcR7ZMU1rf3XXsmJ1166rMW6l0veqFKD04p0KY2QWbi/q47UdVEbhzgcsN5pCCzPQQZ6Is1hsvxqvUv6ky7G4Qkl+DhIyHQVJ+4R6pXjB+IfkeY/ynML6woWpP/4eAgo0dxCHd4XS9E4bmm3MuUcSBjROVDfMAv9PJ39NQzPFyY7VaMFHABAWjrpDZhEKvJe+j31No0P8eUG0jJSpk6lE1raEr+kGsPWdxYPTL8/iOOujhoY8BJqLxC/vGngRcyIKzPpEEUBX/j8XyykGtVh+JgszL5onchzu/HfSQCeOlfGG8QpAfVREQrnEHlcXGrlNUfBfqH1kLNFXBuctzgpUSv3JupCzOzj91hUjvRCDXUFSKB5YJepSktd1OT2oLWH5GAnEInBMVWunfBvVKQVL0UOGSgmSPcCuHHFIZpL8s4vIuo8R5hVW/uI4XcFWDRB0xHfNaY=
  on:
    tags: true
    branch: master
